name: Weekly updates

on:
  schedule:
    - cron: "15 4 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Patch Gradle Repositories
        run:
          sed -ni '/https:\/\/maven.aliyun.com\/repository\/public/{h;n;/https:\/\/repo1.maven.org\/maven2/!{:a;N;/https:\/\/maven.aliyun.com\/repository\/public/!ba;x;H;n};x;H;x};p' repositories

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: ShadowJar

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Rename Weekly
        run: |
          mkdir release
          mv velocity/build/libs/MultiLogin-Velocity-Build_*.jar release/

      - name: Publish Weekly
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "weekly"
          draft: false
          prerelease: true
          title: "MultiLogin Weekly updates"
          files: release/*.jar
